version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./Backend/src/.env

  frontend:
    build: ./prvia-frontend-app
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    env_file:
      - ./Backend/src/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
